name: release
# cf. https://github.com/kazup0n/rust-draft-release/blob/main/.github/workflows/build.yml

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release-build:
    name: Release Build
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Release build discord-cache-cleaner
        run: cargo build --verbose --release

  push-crates-io:
    name: Push Crates.io
    needs:
      - release-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Push crates.io
        run: |
          cargo publish --verbose --token ${{ secrets.CRATES_IO_ACCESS_TOKEN }}
  # リリースの作成はビルドやcrate.ioへのpushなど諸々の作業が終わってから行う必要がある
  # そのため、以下の条件を満たしておく
  #  - jobs.create-release.needs で、上部の jobs を指定する。(指定した jobs が成功し正常終了するまでこの jobs を走らせたくないため)
  #  - 必ず jobs の下部に書くこと (これは jobs.create-release の実行が最後のため)
  create-release:
    name: Create release (draft)
    needs:
      - release-build
      - push-crates-io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            # Release ${{ github.ref }}
            
            ## Installations
            
            ### Usage crate.io
            
            ```shell
            cargo install discord-cache-cleaner
            ```
          draft: true

# TODO: バイナリを配布する
